### ISSUE TITLE
Add code examples using Apache Flink with Flink Scala API

### ISSUE THREAD

**Issue by geazi-anc** [flink-extended/flink-scala-api#139]
In order to improve the understanding
 of this library and Apache Flink for those who have never tried it before, I think a directory in the repo with code examples is a good way to start.
 
 Examples both using SBT and Scala CLI, where the last is a great tool to build Flink scripts. In this [repository](https://github.com/novakov-alexey/flink-sandbox), by @novakov-alexey, there are many useful codes to move to here.

**Comment by novakov-alexey** [comment]
Thanks for proposal. I think it is great idea. Feel free to add those example into separate sub-module
