### ISSUE TITLE
Which Apache Flink versions will be supported

### ISSUE THREAD

**Issue by novakov-alexey** [flink-extended/flink-scala-api#7]
What Flink versions this library needs to support? I assume Scala users might want to use not only the latest Flink version, but also one or two previous versions. Any ideas what can we do to cover multiple versions or should we just stick to latest one and rely on non-breaking changes in Flink 1.x public Java API?

**Comment by shuttie** [comment]
We can make a cross-build, like it's done for [spark-testing-base](https://github.com/holdenk/spark-testing-base)

**Comment by novakov-alexey** [comment]
Done in this commit: https://github.com/flink-extended/flink-scala-api/commit/5f7c46d2f2a1057636dbfed23d116d1bb76701ee
Further improvements are welcome.
