### ISSUE TITLE
Fix Unstable Test

### ISSUE THREAD

**Issue by novakov-alexey** [flink-extended/flink-scala-api#70]
We have one test which fails randomly in GitHub CI. Example: https://github.com/flink-extended/flink-scala-api/actions/runs/6855224529

**Comment by buinauskas** [comment]
I would be glad to look at it, but the build has already expired, is this still relevant?

**Comment by novakov-alexey** [comment]
@buinauskas it would be great. I think it is still relevant. I believe there we have some race-condition. I have seen it mainly in CI job.

**Comment by buinauskas** [comment]
Do you know which test is that? The builds and their logs have already expired so it's difficult to troubleshoot with that little information.

**Comment by novakov-alexey** [comment]
I think it was this test: [ExampleTest](https://github.com/flink-extended/flink-scala-api/blob/1363c73e5191f65ed85adffb4b64a808b90c6755/src/test/scala/org/apache/flinkx/api/ExampleTest.scala#L16)

**Comment by novakov-alexey** [comment]
Hopefully this is the right fix to close. Thanks again @buinauskas
