### ISSUE TITLE
Behave like the grown ups

### ISSUE THREAD

**Issue by hicolour** [flink-extended/flink-scala-api#78]
I think you guys forget mentioning from where actually it was forked.

This project is a community-maintained fork of  [findify/flink-scala-api ](https://github.com/findify/flink-scala-api )cross-built for scala 2.12, 2.13 and 3.x.

**Comment by shuttie** [comment]
I'm the original author of findify/flink-scala-api and flink-adt code. I left Findify in 2022, and my committer access for these repos was revoked. As both these projects were used in the community, we multiple times tried to contact Anze, the Findify CTO - and got no response. I can provide you screenshots of such attempts if needed.

As the project license allows forking, to keep these projects alive we made the fork. To be more constructive, @hicolour what is your suggestion here?

**Comment by novakov-alexey** [comment]
@shuttie thanks for your reply.
I think we do not really care whether original repo is mentioned or not. The important thing is that the project has been rescued from being abandoned. @hicolour you should be greatful that this project is now maintained for free in our spare time and you can use it for work or hobby. 

Instead you created this issues with weird title "Behave like the grown ups" trying to insult us, what is your point?
