### ISSUE TITLE
Runtime error when using a List in a case class

### ISSUE THREAD

**Issue by erwan** [flink-extended/flink-scala-api#8]
I'm trying to use List in my model, however when I do that I have runtime exception during my tests. It seems like I end up with a broken model, with a List that throws whatever I do with it. I'm getting a `java.util.NoSuchElementException: head of empty list` exception from inside the Scala standard lib, so it's neither empty nor containing valid values.

I created a repro as a new test in this branch: https://github.com/erwan/flink-scala-api/commit/2d339dcdbb831fb712905d5991d0ed694180d481

Is there anything I should do differently here? Or maybe that would be a bug in the library?

(migrated from https://github.com/findify/flink-adt/issues/71 as the same issue is present in this new lib)

**Comment by novakov-alexey** [comment]
Hi @erwan,

Thanks for the test!
 
Can you try to use this:
```scala
import org.apache.flink.api._
```
instead of this
```scala
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment
import org.apache.flink.streaming.api.datastream.DataStream
``` ?

**Comment by erwan** [comment]
That worked, thank you!

**Comment by novakov-alexey** [comment]
Ok, great. I think we need pull Migration section in the readme file to the top. It shows these imports to be used.
