### ISSUE TITLE
UUID type information support

### ISSUE THREAD

**Issue by buinauskas** [flink-extended/flink-scala-api#84]
There's no out-of-the-box UUID type information support and I'm happy to implement type information for it so that I and others could use it, the question is whether this is something this library intends to do or it's up to the user to deal with.

Thanks!

**Comment by novakov-alexey** [comment]
@buinauskas which class for UUID do you mean?

**Comment by buinauskas** [comment]
Sorry, should've been more explicit, I've meant `java.util.UUID`.

**Comment by novakov-alexey** [comment]
Got it, yes, we can add it as well. 

At some point in future, we might need to move some Java "standard" TypeInformations into own Scala object to let people opt-out from importing all of them automatically. We will see.
